### ISSUE TITLE
CsvDataLoader and encoding

### ISSUE THREAD

**Issue by samihuutoniemi** [zzzprojects/EntityFramework-Effort#102]
I just tried out the Effort.EF6, and it seems to work fine! But using the CsvDataLoader does not take encoding into account. When the file has special characters, it gets garbled. A fix would be, in CsvTableDataLoader, to change CreateDataReader to this:

![image](https://user-images.githubusercontent.com/2758838/37090028-08948966-2203-11e8-818f-fa1e00e9eaad.png)

And obviously, allowing to pass in the preferred encoding would make it generic.

**Comment by JonathanMagnan** [comment]
Hello @samihuutoniemi ,

Do you think you could provide us a test project with this issue?

It will make easier/faster for my developer to getting started for investigating it.

_We now always ask for a project since we found out that most issues are missing some essential information or are resolved by the requestor when creating it_

_(Even if the issue seem very easy to reproduce, by getting a test project, it allow us to give a faster support and better experience for the support of all our free libraries)_

Best Regards,

Jonathan

**Comment by samihuutoniemi** [comment]
I have only used Effort at work, and the code is very internal. I don't have a test project available right now, but if I can I will.
