### ISSUE TITLE
Incorrect navigation property fixup on SaveChanges

### ISSUE THREAD

**Issue by camitz** [zzzprojects/EntityFramework-Effort#117]
Hello!

It doesn't seem correct that the last assert should fail.

```
Assert.That(d.TransactionAuxiliary,Is.Not.Null);
db.SaveChanges();
Assert.That(d.TransactionAuxiliary, Is.Not.Null);
db.SaveChanges();
Assert.That(d.TransactionAuxiliary, Is.Not.Null);
```

**Comment by JonathanMagnan** [comment]
Hello @camitz ,

Do you think you could provide a "working" project example/test with this issue?

It will make easier/faster for my developer to getting started for investigating it.

_You can send it to info@zzzprojects.com if you need to keep the source private_

_We now always ask for a project since we found out that most issues are missing some essential information, have some syntax mistake or are resolved by the requestor when creating it_

_(Even if the issue seem very easy to reproduce, by getting a test project, it allow us to give a faster support and better experience for the support of all our free libraries)_

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @camitz ,

There is some critical information in your code to reproduce it.

Here is an example with your code of what we normally require:

```csharp
using System;
using System.ComponentModel.DataAnnotations;
using System.Data.Common;
using System.Data.Entity;
using System.Windows.Forms;

namespace Effort.Lab.EF6
{
    public partial class Form_Request_TransactionAuxiliary : Form
    {
        public Form_Request_TransactionAuxiliary()
        {
            InitializeComponent();

            var connection = My.ConnectionFactory();//DbConnectionFactory.CreateTransient();

            var addToDbSet = false;

            // TEST
            using (var db = new EntityContext(connection))
            {
                var d = new Transaction();

                db.Transactions.Add(d);

                d.TransactionAuxiliary = new TransactionAuxiliary
                {
                    Transaction = d
                };


                if (addToDbSet) db.TransactionAuxiliaries.Add(d.TransactionAuxiliary);

                db.SaveChanges();

                if (d.TransactionAuxiliary == null) throw new Exception("Fails if addToDbSet");

                db.SaveChanges();

                if (d.TransactionAuxiliary == null) throw new Exception("Fails if !addToDbSet");
            }
        }

        public class EntityContext : DbContext
        {
            public EntityContext(DbConnection connection) : base(connection, true)
            {
            }

            public DbSet<TransactionAuxiliary> TransactionAuxiliaries { get; set; }
            public DbSet<Transaction> Transactions { get; set; }

            protected override void OnModelCreating(DbModelBuilder modelBuilder)
            {
                modelBuilder.Entity<Transaction>().HasOptional(x => x.TransactionAuxiliary)
                    .WithRequired(x => x.Transaction);

                base.OnModelCreating(modelBuilder);
            }
        }

        public class Transaction
        {
            public int TransactionID { get; set; }

            public TransactionAuxiliary TransactionAuxiliary { get; set; }
        }

        public class TransactionAuxiliary
        {
            private Transaction _transaction;

            [Key] public int TransactionAuxiliaryID { get; set; }

            public virtual Transaction Transaction
            {
                get => _transaction;
                set
                {
                    //commenting produces test failures.
                    //_transaction = value; 
                }
            }
        }
    }
}
```

Unfortunately, since we have the same error with `Entity Framework`, there is no so much we can currently do at this moment.

Very soon, we will release a new product Z Entity Framework Classic which we will be able to fix some issue like this one directly in our EF6 fork.

But for now, the bug reside in EF so there is nothing we can do.

Let me know if that answer correctly to this issue.

Best Regards,

Jonathan

**Comment by camitz** [comment]
Looking forward to your new product. I've likes this one very much so far. 

Thank you for your help with this issue.

All the best

**Comment by JonathanMagnan** [comment]
It will be eventually be compatible with our as well ;)
