### ISSUE TITLE
Self Reference Foreign Key Not Null column throws Invalid Key 

### ISSUE THREAD

**Issue by PrabhujiMudragalla** [zzzprojects/EntityFramework-Effort#142]
Hi Team, 

We are trying to insert data for our tables but we are facing Invalid Key exception. 
As the table contains Self Reference Foreign key in it and also it is not null column we are facing this exception. 

How can we fix this issues without changing the table schema? 
Thanks 
Prabhuji

**Comment by JonathanMagnan** [comment]
Hello @PrabhujiMudragalla ,

Do you think you could provide a project sample with this issue?

It will help my developer investigate the issue more efficiently.

_We now always ask for a project sample even if the issue is easy to reproduce. As a free product, we must find some way to save time to offer an overall better experience for everyone and release fixes faster._

_You can send it to: info@zzzprojects.com if you need to keep the source private_

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by PrabhujiMudragalla** [comment]
It's difficult to share the project sample. 

This issue is reproducible with self reference foreign key and not null column 
Example:
public class Contact
{
    public Guid Id {get;set;}
    public string Name {get;set;}
    public Guid SpouseId {get;set;}

    public Contact Spouse { get; set; }
}

**Comment by JonathanMagnan** [comment]
Hello @PrabhujiMudragalla ,

Can you provide a full example using this class?

Unfortunately, someone needs to provide us a code that reproduces the issue if you want we look at it. We do not longer want to make all research on our side to reproduce it as it cost us money to maintain this free library.

**Comment by JonathanMagnan** [comment]
Hello @PrabhujiMudragalla ,

This issue will be closed since we haven't heard back from you.

Feel free to reopen if you can provide further information.

Best Regards,

Jonathan
