### ISSUE TITLE
ClearTables does not reset Identity _Insert

### ISSUE THREAD

**Issue by Gabbbou** [zzzprojects/EntityFramework-Effort#158]
Hi,

When inserting element having an identity_insert property it works fine first. At the end of each tests I do a ClearTables, but when the second test starts, it tries to insert 1 again and then I get a identity violation.

I think CleanrTables should reset identity as well.

Thanks,
Gabriel

**Comment by JonathanMagnan** [comment]
Hello @Gabbbou ,

Thank you for reporting.

We will look if there is a reason why `ClearTables` doesn't reset the identity.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello @Gabbbou ,

I have talked with my developer.

He made some test and everything seem to work, but he believes that he knows what happen.

If your context is not disposed of yet and you re-use it, you need to pass it to the method `ClearTables()`

```csharp
connection.ClearTables(context);
```

or use a new Context. That is be caused because table are cleared, but the `ChangeTracker` still own entities that have previously inserted which may cause some key conflict.

If you do not believe that's your issue, please provide us with a project sample with this error and we will investigate it.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Thank you for the code @Gabbbou ,

My developer will look at it.

**Comment by JonathanMagnan** [comment]
Hello @Gabbbou ,

My developer tried it and everything seems to work. Do you think you could provide him a project sample with the issue?

Here is what he has done:

[InMemoryConnectionStrategy.txt](https://github.com/zzzprojects/EntityFramework-Effort/files/2757072/InMemoryConnectionStrategy.txt)

**Comment by JonathanMagnan** [comment]
Hello @Gabbbou ,

This issue will be closed since we haven't heard back from you.

We will be happy to re-open it as soon as you provide more information.

Best Regards,

Jonathan
