### ISSUE TITLE
Load CSV data for same table name (different structure) in different schema

### ISSUE THREAD

**Issue by midway500** [zzzprojects/EntityFramework-Effort#178]
### Description
We have a need to load the database via CSV for the same table name (with different structure) for different schema.  When I am trying to use the CSV file name as Schema_TableName.csv but it does not work.  Sometimes, it tries to load the data intended for one schema into another and causes error.

**Comment by JonathanMagnan** [comment]
Hello @midway500 ,

Do you think you could provide a project sample with this issue?

It will help my developer investigate the issue more efficiently.

_We now always ask for a project sample even if the issue is easy to reproduce. As a free product, we must find some way to save time to offer an overall better experience for everyone and release fixes faster._

_You can send it to: info@zzzprojects.com if you need to keep the source private_

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by midway500** [comment]
Will provide a project sample.

**Comment by JonathanMagnan** [comment]
Hello @midway500 ,

I believe we never got the project.

We will close the issue but feel free to provide the project anytime and we will re-open it.

**Comment by midway500** [comment]
Please re-open the ticket.

I am sending the a sample project to info@zzzprojects.com

Go to the Sample.Effort.UnitTest project and run the TestMethod in UnitTest1.  The test will fail with error:

> Message: Test method Sample.Effort.UnitTest.UnitTest1.TestMethod1 threw exception: 
Effort.Exceptions.EffortException: Unhandled exception while trying to initialize the content of 'Table<dbo_Table1>' table ---> Effort.Exceptions.EffortException: An unhandled exception occurred while trying to assign value '1/1/2000 12:00:00 AM' to Property 'Column1' of type 'System.Int32' during entity initialization for table 'Effort.Internal.DbManagement.Schema.TableName' ---> System.InvalidCastException: Specified cast is not valid.

**Comment by JonathanMagnan** [comment]
Hello @midway500 ,

Sorry for the delay, my developer finally got time to look at it.

Could you try the v2.2.4 and let us know if everything works as expected in this version?

Best Regards,

Jonathan

**Comment by midway500** [comment]
Will give it a try.

**Comment by midway500** [comment]
Version 2.2.4 corrects my issue.  Thank you so much.
