### ISSUE TITLE
How to you create a connection with IdentityDbContext ?

### ISSUE THREAD

**Issue by tawani** [zzzprojects/EntityFramework-Effort#204]
### Description
Describe the issue or proposed feature.
I am trying to create an instance of an AppDbContext that inherits from IdentityDbContext 
The problem is, IdentityDbContext requires a DbCompiledModel which isn't found anywhere.
How would you create such a connection?

**Comment by JonathanMagnan** [comment]
Hello @tawani ,

I might be wrong since I never used it but it doesn't look that `IdentityDbContext` require this DbCompiledModel as a parameter. Or Perhaps I misunderstand the question.

You use the `IdentiytDbContext` pretty much like you use a `DbContext`: https://entityframework.net/knowledge-base/50377705/asp-net-core--add-data-to-identitydbcontext-or-use-dbcontext

Best Regards,

Jon

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
