### ISSUE TITLE
Entity Framework Plus - InsertFromQuery command - doesn't wotk

### ISSUE THREAD

**Issue by gnevashev** [zzzprojects/EntityFramework-Effort#214]
## 1. Description
Used Nuget packages: 
**Entity Framework 6.4**, 
**Effort EF v2.2.16**, 
**Z.EntityFramework.Plus.EF6 v6.13.12**

Implemented similar fuctionality: https://entityframework-extensions.net/insert-from-query
When the query executed on SQL Server everything is working fine, with Effort DB i receive following error

## 2. Exception
```
System.Exception
  HResult=0x80131500
  Message=Stream not found (Conceptual).
  Source=Z.EntityFramework.Extensions
  StackTrace:
   at .(DbContext this, String )
   at .(DbContext this, List`1 , String )
   at .(DbContext )
   at .(DbContext )
   at DbContextExtensions.GetModel(DbContext this)
   at `1.(IQueryable`1 , Action`1 )
   at `1.Execute(IQueryable`1 query, Action`1 batchInsertBuilder)
   at DbContextExtensions.[](IQueryable`1 , Action`1 )
   at DbContextExtensions.[](IQueryable`1 , String , String , String , Type , Expression`1 )
```
Can I somehow use Effort DB with this command?
Thank you in advance.

**Comment by JonathanMagnan** [comment]
Hello @gnevashev ,

The current error you are receiving is not related with this feature in particular. We cannot read your model for an unknown reason (We can know it with the `GetModel` in the stack trace).

If you provide a runnable project with this error, we will be happy to fix this part (you can send it in private here: info@zzzprojects.com)

However, even once fixed, the `InsertFromQuery` will not still work since this method does not support yet `Effort` and we currently have no short-term plan of doing this (time is unfortunately missing)

Best Regards,

Jon

---
**Sponsorship**
[Help us improve this library](https://github.com/sponsors/zzzprojects)

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](https://entityframework-extensions.net/) • [Bulk Operations](https://bulk-operations.net/) •  [Dapper Plus](https://dapper-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](https://eval-expression.net/) • [SQL Eval Function](https://eval-sql.net/)

**Comment by gnevashev** [comment]
Hi @JonathanMagnan ,

thank you for your answer. I hope some day you will also implement this feature!

Best Regards,
Evgeny
