### ISSUE TITLE
Extreme performance drop after switching to code first

### ISSUE THREAD

**Issue by wertzui** [zzzprojects/EntityFramework-Effort#39]
I have about 1000 Tests running with Effort.
I use CreateTransient so that each Test gets it's own fresh Database.
I recently switched from Database First to Code First and noticed a significant performance drop.
The Tests used to run in about 40 Minutes and are now taking about 2.4 hours to complete.
This is an increase of about 6 seconds per Test.

I did a lot of profiling and the problem seems to come from code first creating a new database for every test.
The drop comes from System.Data.Entity.Internal.InternalContext.InitializeDatabase() which is called whenever an operation is executed on a new Connection that I created using CreateTransient(...).

I tried turning of DB Initialization with Database.SetInitializer<MyContext>(null), but then I get an error from Effort that says I need to initialize the Database when using code first.

I also tried using CreatePersistent and using a Transaction on the connection which gets rolled back in TestInitialize, but the Rollback was not executed to the Data from Test1 ended up in Test2.

Is there anything else I can do to return the performance to a normal Level?
I would be happy to create a Pull Request if there is anything that I can change in the Effort code too.

**Comment by JoeShmoel** [comment]
Hi,
Did you ever get a solution for this problem? We have the same issue.

**Comment by JonathanMagnan** [comment]
Hello @wertzui, @JoeShmoel ,

Is it possible for you to create a sample project with this issue?

We are currently making an issue cleanup and make sure we focus on issues people still require since it will be impossible to make them all (It's a free library!). Since that's has been a long time since this issue has been answered, it might also be already fixed.

Best Regards,

Jonathan

**Comment by jlonka** [comment]
Hi Jonathan
It is quite easy to replicate I dont have a project that you can use unfortunately however basically its as simple as.. create a couple of hundred objects in a class when you create it call savechanges on the entity framework and then move to another object and reference the previous object. To me it looks like the object creation and linking of the object when it is tracked between calls to save changes is the issue. A work around that we found is to assign all objects a fixed ID and only call save changes at the end of adding everything to the context. Hope that gives you enough information to simulate the problem and an example of a speeded up solution.

**Comment by JonathanMagnan** [comment]
Hello @jlonka ,

Thank you for the additional information. We will look at it very soon and will ask if something else is missing.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @jlonka , @wertzui ,

I'm not sure if both of your issues were similar.

From what I understand, @wertzui has some issue whenever a new effort connection was created since all the migrations were done every time.

The v1.3.8 has been released.

In this version, we added a new method `ClearTables` that clear all data and reset the identity. Only the `__migrationHistory` tables keep his data.

```csharp
var connection = (EffortConnection)DbConnectionFactory.CreateTransient();

// ...code...

connection.ClearTables();
```

So performing multiple tests with the same connection should be WAY faster by clearing all tables instead of creating a new connection every time.

@jlonka , Unless I'm wrong, I believe your issue was different. If that's the case, could you open a new issue and provide us with additional information. We were not able to understand correctly your explanation.

Best Regards,

Jonathan

**Comment by jlonka** [comment]
@JonathanMagnan Thanks for the update. I will see if I can get a few hours to put an example together of the problem. In fairness the cleartables may actually resolve it by accident because the clear tables will reuse the connection and you can reset the data whilst I was resetting the connection to a "known state" each test. I will try to replicate the problem and try the clear tables and reload and see if it resolves the problem as well. Ps, love effort, great work thanks for the "effort" that you put into it for the community it is appreciated even if people dont tell you all the time.

**Comment by JonathanMagnan** [comment]
Thank a lot @jlonka for your good word ;) It always appreciated ;)
