### ISSUE TITLE
NUnit, first run after a build, slow

### ISSUE THREAD

**Issue by urig** [zzzprojects/EntityFramework-Effort#43]
Cross-posting [this issue](https://effort.codeplex.com/workitem/764) from CodePlex as I'm experiencing the exact same issue:

> Hey,  
> I started a new project in which I want to make some integration testing using Effort. Since it's the beginning of the project, I'm often rebuilding the test project after small changes. When I first run the tests, it takes me around 10 seconds to run a couple of tests. After that it's under a second.  
> Any recommendations on this issue?

**Comment by tamasflamich** [comment]
Hi urig - Sorry for the late response. How many tests do you run?

Having slower startup time is common problem for people using larger data schemas, so I suspect this is the case for you as well, right?

**Comment by mortb** [comment]
I too experience this problem. One test takes about 10 seconds and then the tests are fast. Is it possible to optimize the code?

**Comment by JonathanMagnan** [comment]
Hello,

Is there anyone of you could provide an example of a test project that has this issue?

I know it has been a long time since this issue has been created but we are currently cleaning some old issue and want to make sure we focus our time on some fix on issues that people still require.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello,

This issue will be closed since none provided information.

We understand this issue has been created long ago, but since that's a free library, we want to make sure to work on an issue that is still active since we cannot make them all.

Feel free to reopen if you can provide further information.

Best Regards,

Jonathan
