### ISSUE TITLE
Initializing two dbContext data failed

### ISSUE THREAD

**Issue by leewangq** [zzzprojects/EntityFramework-Effort#44]
when I initialized two dbcontext data ,it throw exception at the method of dbcontext's SaveChanges().
like that:

{"Table 'XXXXXX' was not found. The database was probably not initialized.\r\n\r\nIf using CodeFirst try to add the following line:\r\ncontext.Database.CreateIfNotExists()"}

**Comment by tamasflamich** [comment]
Hi leewangq - sorry for the late response. Can you provide a little proof of concept code for your problem. Unfortunately this isn't going to be enough for me to reproduce.

**Comment by leewangq** [comment]
sorry for the late response, I found the error was not caused by Effort, it was my framework's error, sorry for  
that!

**Comment by JonathanMagnan** [comment]
Hello @Jon,

This issue will be closed since it has been resolved by yourself ;)

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)
