### ISSUE TITLE
CsvDataLoader database is not initialized

### ISSUE THREAD

**Issue by AlekseyKovalevsky** [zzzprojects/EntityFramework-Effort#55]
Hello, 
I want to initialize my database with data using csvdataloader. So, I'm trying to do the following ( as in guide) 
```
        [Test]
        public void IsUserModelPropertiesMappedCorrectly()
        { 
            var dataLoader = new CsvDataLoader(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, TestDataFolderName));
            var inMemoryDbConnection = Effort.DbConnectionFactory.CreateTransient(dataLoader);

            using (var ctx = new AppDbContext(inMemoryDbConnection))
            {
                
                var firstUser = ctx.Set<User>().First(); // here I'm getting the exception  
                .................................       //  Database has not been initialized.If using CodeFirst  try to add the following line:  context.Database.CreateIfNotExists()          

            }
        }
```
My AppDbContext looks like this 
```
public class AppDbContext : DbContext
    {
        public AppDbContext(DbConnection connection, IDatabaseInitializer<AppDbContext> dbInitializer = null)
            : base(connection, true)
        {
            Database.SetInitializer(dbInitializer);         
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();

            modelBuilder.Configurations.Add(new UserTypeConfiguration());
            modelBuilder.Configurations.Add(new RoleTypeConfiguration());
            modelBuilder.Configurations.Add(new PostTypeConfiguration());
            modelBuilder.Configurations.Add(new CommentTypeConfiguration());
            modelBuilder.Configurations.Add(new PermissionTypeConfiguration());
            modelBuilder.Configurations.Add(new RecordTypeConfiguration());
        }
    }
```
And even if I execute the ``context.Database.CreateIfNotExists()``, the database is created but is not initialized with my csv data? 
So, could you explain why I'm getting this result?

**Comment by JonathanMagnan** [comment]
Hello @AlekseyKovalevsky ,

Is it possible for you to create a sample project with this issue? My developer was not able to get this error.

We are currently making an issue cleanup and make sure we focus on issues people still require since it will be impossible to make them all (It's a free library!).

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello,

This issue will be closed since none provided information.

We understand this issue has been created long ago, but since that's a free library, we want to make sure to work on an issue that is still active since we cannot make them all.

Feel free to reopen if you can provide further information.

Best Regards,

Jonathan
