### ISSUE TITLE
Interpreting 0 and 1 as booleans

### ISSUE THREAD

**Issue by johnknoop** [zzzprojects/EntityFramework-Effort#60]
Hi!

I've exported some tables from our MySQL db to csv files. However, Effort complains when loading the data, because boolean columns are zeros and ones (as in a db table). It seems to want the text "true" or "false". Is there anyway to configure it to accept data the way it looks when exporting from a database?

**Comment by JonathanMagnan** [comment]
Hello @johnknoop ,

Is it possible for you to create a sample project with this issue?

We are currently making an issue cleanup and make sure we focus on issues people still require since it will be impossible to make them all (It's a free library!).

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello,

This issue will be closed since none provided information.

We understand this issue has been created long ago, but since that's a free library, we want to make sure to work on an issue that is still active since we cannot make them all.

Feel free to reopen if you can provide further information.

Best Regards,

Jonathan
