### ISSUE TITLE
Incorrect number of arguments for constructor

### ISSUE THREAD

**Issue by lommez** [zzzprojects/EntityFramework-Effort#63]
Is there any limitation on Effort when making a query with a group by clause?
When running my unit tests with Effort i receive that message "Incorrect number of arguments for constructor" but the same problem doesn't occurs when running in mssql database.
Is that a known issue?

Thanks!

**Comment by CoreyCaldwell** [comment]
+1 For this. This error occurs on versions higher than Effort.EF6.1.1.4 (occurs on 1.1.5, 1.2.0 & 1.3.0). You might try downgrading to 1.1.4 in the meantime

**Comment by lommez** [comment]
Thanks Corey!
I'll try that.

**Comment by davonium** [comment]
+1.
I did some investigation into the problem and found the following:
```c#
context
    .Entities
    .GroupBy(
        x => new
        {
            x.Value1,
            x.Value2,
            x.Value3,
            x.Value4,
            x.Value5,
            x.Value6,
            x.Value7
        })
    .Select(
        x => new
        {
            Count = x.Count()
        }).ToArray();
```
^^ is the simplest way to reproduce the issue.

The commit causing the issue is: caa2e13
where the constant `LargeDataRowAttribute.LargePropertyCount` is changed from 32 to 8.
Unfortunately it's a constant, so it can't be changed runtime...

Actually the problem exists also in Effort.EF6.1.1.4, but you are not very likely to group an entity on 30ish properties.

I am not sure why the DataRow types handles "Large" types differently, but since they do they must be created in a different way if they are - `Expression.New(ctr, args, members)` (as in `TransaformVisitor.Visit(DbGroupByExpression)`) will not work the same way as for small DataRows.

**Comment by askrinnik** [comment]
I faced the same issue with query:
var res = _context.WorkItems
        .GroupBy(wi => wi)//.ToArray()
        .Select(group => new  {  Hours = group.Sum(wi => wi.TimeSpent) })
        .ToArray();
If I uncomment ToArray() after ToArray(), all works properly
If I remove anonimous class creation it also works properly

Any updates?

**Comment by dcorriveau-omniscient** [comment]
I have the same issue with this syntax:
`group tablename by new { ...`
(16 fields)

> Incorrect number of arguments for constructor

**Comment by JonathanMagnan** [comment]
Hello all,

The v1.3.8 has been released.

We have added a new property `DbConnectionFactory.LargePropertyCount = 16;` to let you gets and sets the LargePropertyCount value.

By increasing the amount, you should no longer get the problem.

Let us know if everything works as expected.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello all

This issue will be closed since it has been resolved.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan

**Comment by hanushans** [comment]
Hi, 
I'm writing tests for a database first application so I'm using 
`Effort.EntityConnectionFactory` instead of 
`Effort.DbConnectionFactory` and I'm facing the same issue with "Incorrect number of arguments for constructor" and a group by clause.
Is there a way to solve this for `EntityConnectionFactory`?

Thanks a lot!
