### ISSUE TITLE
Explicit message for exception : System.Reflection.TargetInvocationException (No coercion operator is defined between types '{0}' and '{1}')

### ISSUE THREAD

**Issue by thetopic** [zzzprojects/EntityFramework-Effort#64]
I installed effort via Nuget.

During the call to CreateTransient I had this exception: ```cs System.Reflection.TargetInvocationException
``` with the following message: `csharp No coercion operator is defined between types 'Byte' and 'String'`, without any additional index.

I downloaded the sources to see where the exception was, it was triggered in :

```cs
Effort.Internal.DbManagement.Schema.Configuration.RelationConfiguration.cs

    public void Configure (AssociationInfo associationInfo, DbSchemaBuilder builder) {
         ....
         Delegate primaryToForeignConverter =
                CreateConverter (
                    PrimaryToForeignConverterMethod,
                    PrimaryKeyInfo,
                    ForeignKeyInfo,
                    RelationshipConstraints);
         ....
    }
```

In the the stack trace I had more information and see where the problem came from:

In my database I have two tables that are linked via a primary key composite by two fields, in the first table the fields are ordered in one direction and in the second table in a different direction :

**Tbl1 (Col1 varchar, Col2 tinyint) <-----> Tbl2 (Col2 tinyint, Col1 varchar)**

With the debug I could see the problem:

```cs
PrimaryKeyInfo = Tuple (String, Byte)
ForeignKeyInfo = Tuple (Byte, String)
```
I was also able to see the problematic tables..

I corrected the order of the columns in the database, and now it works.

This exception should be intercepted to provide the information needed to find the problematic tables and focus on the type of problem: primary and foreign keys that are composed of several fields but ordered differently.

_In writing this message I am thinking that I was lucky to have different types, if I did not have this exception the join would have been made on the wrong columns ?_

**Comment by JonathanMagnan** [comment]
Hello @thetopic ,

Is it possible for you to create a sample project with this issue? My developer was not able to get this error.

We are currently making an issue cleanup and make sure we focus on issues people still require since it will be impossible to make them all (It's a free library!).

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Entity Framework Classic](http://entityframework-classic.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by JonathanMagnan** [comment]
Hello,

This issue will be closed since none provided information.

We understand this issue has been created long ago, but since that's a free library, we want to make sure to work on an issue that is still active since we cannot make them all.

Feel free to reopen if you can provide further information.

Best Regards,

Jonathan
