### ISSUE TITLE
Update tutorial code to reflect current library

### ISSUE THREAD

**Issue by MarkTiedemann** [zzzprojects/EntityFramework-Effort#69]
That would be amazing. :)

**Comment by JonathanMagnan** [comment]
Hello @MarkTiedemann ,

We are currently re-working the documentation of all our libraries.

We made a lot of improvement on .NET FIddle (https://dotnetfiddle.net/) to make it support `Entity Framework`.

So some documentation update will be soon be made.

Even if that request not completed, I will close it since we are currently trying to clean up all opened issues. Feel free to re-open it if that has not been made before the end of `2018`

Best Regards,

Jonathan
