### ISSUE TITLE
Two DbContexts on the same connection results in 2 '__MigrationHistory' tables.

### ISSUE THREAD

**Issue by Sventric** [zzzprojects/EntityFramework-Effort#82]
We have a system where an application consists of 2 DbContexts, 1 'readonly' dataset of administrative data (containing details required by the second). The second DbContext is using the first DbContext to determine the name of the table and somewhat. When the second DbContext is initialized there occurres a InvalidOperationException on a SingleOrDefault call. When debugging this it shows 2 '__MigrationHistory' tables.
![effort_multiple_migrationhistory_tables](https://user-images.githubusercontent.com/9800855/30796157-27db3c46-a1d1-11e7-91b0-f611c539a58e.png)

**Comment by JonathanMagnan** [comment]
Hello @Sventric ,

Updating the version of `NMemory` to v2.0.2 should fix the issue. The code should not longer create a duplicate table.

A new version (using the latest NMemory version) should be available very soon.

I knew it's has been a long time since you created the issue, but if you can test it, that would be great.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello,

This issue will be closed since it has been probably resolved in the latest release.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
