### ISSUE TITLE
The provided parameter object is incompatible

### ISSUE THREAD

**Issue by BERNINIGIT** [zzzprojects/EntityFramework-Effort#88]
I am trying to add a SQLParameter of type SqlDbType.Structured to the list of parameters of a DBCommand when I get the exception: The provided parameter object is incompatible

**Comment by JonathanMagnan** [comment]
Hello @BERNINIGIT ,

Is it possible for you to create a sample project with this issue?

We are currently making an issue cleanup and make sure we focus on issues people still require since it will be impossible to make them all (It's a free library!). Since that's has been a long time that this issue has been answered, it might also be already fixed.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello,

This issue will be closed since none provided information.

We understand this issue has been created long ago, but since that's a free library, we want to make sure to work on an issue that is still active since we cannot make them all.

Feel free to reopen if you can provide further information.

Best Regards,

Jonathan
